## This file is a general .xdc for the ALINX AX7021 board
## To use it in a project:
## - uncomment the lines corresponding to used pins
## - rename the used signals according to the project
set_property PACKAGE_PIN A17 [get_ports btns_tri_i[0]]
set_property IOSTANDARD LVCMOS33 [get_ports btns_tri_i[0]]

set_property PACKAGE_PIN R7 [get_ports leds_tri_o[0]]
set_property IOSTANDARD LVCMOS33 [get_ports leds_tri_o[0]]

set_property PACKAGE_PIN A16 [get_ports leds_tri_o[1]]
set_property IOSTANDARD LVCMOS33 [get_ports leds_tri_o[1]]

set_property PACKAGE_PIN G16 [get_ports hdmi_clk]
set_property PACKAGE_PIN H22 [get_ports {hdmi_d[0]}]
set_property PACKAGE_PIN G22 [get_ports {hdmi_d[1]}]
set_property PACKAGE_PIN G17 [get_ports {hdmi_d[2]}]
set_property PACKAGE_PIN F17 [get_ports {hdmi_d[3]}]
set_property PACKAGE_PIN G15 [get_ports {hdmi_d[4]}]
set_property PACKAGE_PIN D15 [get_ports {hdmi_d[5]}]
set_property PACKAGE_PIN E15 [get_ports {hdmi_d[6]}]
set_property PACKAGE_PIN F18 [get_ports {hdmi_d[7]}]
set_property PACKAGE_PIN E18 [get_ports {hdmi_d[8]}]
set_property PACKAGE_PIN H17 [get_ports {hdmi_d[9]}]
set_property PACKAGE_PIN H18 [get_ports {hdmi_d[10]}]
set_property PACKAGE_PIN H19 [get_ports {hdmi_d[11]}]
set_property PACKAGE_PIN H20 [get_ports {hdmi_d[12]}]
set_property PACKAGE_PIN G19 [get_ports {hdmi_d[13]}]
set_property PACKAGE_PIN F19 [get_ports {hdmi_d[14]}]
set_property PACKAGE_PIN G20 [get_ports {hdmi_d[15]}]
set_property PACKAGE_PIN G21 [get_ports {hdmi_d[16]}]
set_property PACKAGE_PIN F21 [get_ports {hdmi_d[17]}]
set_property PACKAGE_PIN F22 [get_ports {hdmi_d[18]}]
set_property PACKAGE_PIN E21 [get_ports {hdmi_d[19]}]
set_property PACKAGE_PIN D21 [get_ports {hdmi_d[20]}]
set_property PACKAGE_PIN D22 [get_ports {hdmi_d[21]}]
set_property PACKAGE_PIN C22 [get_ports {hdmi_d[22]}]
set_property PACKAGE_PIN B21 [get_ports {hdmi_d[23]}]

set_property PACKAGE_PIN E20 [get_ports hdmi_de]
set_property PACKAGE_PIN E19 [get_ports hdmi_hs]
set_property PACKAGE_PIN C17 [get_ports hdmi_nreset_tri_o]
set_property PACKAGE_PIN F16 [get_ports hdmi_vs]
set_property PACKAGE_PIN B22 [get_ports hdmi_i2c_scl_io]
set_property PACKAGE_PIN A22 [get_ports hdmi_i2c_sda_io]

set_property IOSTANDARD LVCMOS33 [get_ports hdmi_i2c_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_i2c_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_clk]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_de]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_hs]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_d[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_vs]

set_property IOSTANDARD LVCMOS33 [get_ports hdmi_nreset_tri_o]


set_property PULLUP true [get_ports hdmi_i2c_scl_io]
set_property PULLUP true [get_ports hdmi_i2c_sda_io]

set_property SLEW FAST [get_ports {hdmi_d[*]}]
set_property DRIVE 8 [get_ports {hdmi_d[*]}]
set_property SLEW FAST [get_ports hdmi_clk]
set_property SLEW FAST [get_ports hdmi_de]
set_property SLEW FAST [get_ports hdmi_hs]
set_property SLEW FAST [get_ports hdmi_vs]

set_property PACKAGE_PIN V12 [get_ports {ad_os[1]}]
set_property PACKAGE_PIN W12 [get_ports {ad_os[0]}]
set_property PACKAGE_PIN U12 [get_ports {ad_convstab}]
set_property PACKAGE_PIN U11 [get_ports {ad_os[2]}]
set_property PACKAGE_PIN U9 [get_ports {ad_rd}]
set_property PACKAGE_PIN U10 [get_ports {ad_reset}]
set_property PACKAGE_PIN T6 [get_ports {ad_busy}]
set_property PACKAGE_PIN R6 [get_ports {ad_cs}]
set_property PACKAGE_PIN U6 [get_ports {first_data}]
set_property PACKAGE_PIN W10 [get_ports {ad_data[0]}]
set_property PACKAGE_PIN W11 [get_ports {ad_data[1]}]
set_property PACKAGE_PIN Y10 [get_ports {ad_data[2]}]
set_property PACKAGE_PIN Y11 [get_ports {ad_data[3]}]
set_property PACKAGE_PIN W8 [get_ports {ad_data[4]}]
set_property PACKAGE_PIN V8 [get_ports {ad_data[5]}]
set_property PACKAGE_PIN AA6 [get_ports {ad_data[6]}]
set_property PACKAGE_PIN AA7 [get_ports {ad_data[7]}]
set_property PACKAGE_PIN AA11 [get_ports {ad_data[8]}]
set_property PACKAGE_PIN AB11 [get_ports {ad_data[9]}]
set_property PACKAGE_PIN AB4 [get_ports {ad_data[10]}]
set_property PACKAGE_PIN AB5 [get_ports {ad_data[11]}]
set_property PACKAGE_PIN AB1 [get_ports {ad_data[12]}]
set_property PACKAGE_PIN AB2 [get_ports {ad_data[13]}]
set_property PACKAGE_PIN Y4 [get_ports {ad_data[14]}]
set_property PACKAGE_PIN AA4 [get_ports {ad_data[15]}]

set_property IOSTANDARD LVCMOS33 [get_ports {ad_os[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_os[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_convstab}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_os[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_rd}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_reset}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_busy}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_cs}]
set_property IOSTANDARD LVCMOS33 [get_ports {first_data}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[15]}]


set_false_path -from [get_clocks clk_fpga_1] -to [get_clocks clk_fpga_0]
set_false_path -from [get_clocks clk_fpga_0] -to [get_clocks clk_fpga_1]


